// <auto-generated />
namespace AuctionSystem.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AuctionPictures1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuctionPictures1));
        
        string IMigrationMetadata.Id
        {
            get { return "202107311045524_AuctionPictures1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
